### PR TITLE
Laravel 7 support

### PR DESCRIPTION
**Pull request by naillizard**

### CODE REVIEW

**Comment by naillizard** [comment]
Damn I think I made a mistake, this shouldn't work with L6, and in composer.json I've included both, maybe v2 should be Laravel 6 and v3 Laravel 7?

**Comment by mlanin** [comment]
As far as I can see in this PR, there is no BC. Why to rise the major version?

**Comment by mlanin** [comment]
Oh, now I see... Remove please 6.0 from composer and I'll make a new tag

**Comment by naillizard** [comment]
Done.

**Pull request merged**
